services:
  # PostgreSQL 数据库
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-surveysys}
    volumes:
      - ./data:/var/lib/postgresql/data:Z
    restart: unless-stopped

  # Deno 后端+前端静态 serve
  server:
    build:
      context: .
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-surveysys}
      PORT: 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    # volumes:
    #   - ./server:/app/server
    #   - ./client/dist:/app/server/public
    restart: unless-stopped
