name: "Dev CI"

on:
  workflow_dispatch:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:18
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: surveysys
        ports:
          - 5432:5432
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          cache: true

      - name: Prisma generate
        working-directory: server
        run: |
          echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/surveysys" >> $GITHUB_ENV
          deno task db:generate

      # Uncomment this step to verify the use of 'deno fmt' on each commit.
      # - name: Verify formatting
        # working-directory: server
        # run: deno fmt --check

      # - name: Run linter
        # working-directory: server
        # run: deno lint

      - name: Run tests
        working-directory: server
        run: deno test -A
